username = input("введите имя пользователя: ")
print(" имя пользователя:",username)
title = input("введите заголовок заметки: ")
print(" заголовок заметки:",title)
content = input("введите описание заметки: ")
print("описание заметки:", content)
status = input("введите статус заметки: ")
print("статус заметки:", status)
created_date = input("Дата создания заметки (пример: 10.11.2024): ")
print("дата создания заметки:",created_date[:5])
issue_date = input("дата истечения заметки (пример: 10.11.2024): ")
print("дата истечения заметки", issue_date[:5])

